
name: Publish Website
on: 
  push:
    branches:
        - master


jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Sass Build
      uses: gha-utilities/sass-build@v0.0.5
      with:
        source: "wp-content/themes/pp/style.scss"
        destination: "wp-content/themes/pp/style.css"
        outputStyle: compressed
        indentType: space
        indentWidth: 4
        sourceComments: false
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USER }} 
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        #log-level: verbose
        #port: 22
        #security: loose
        args: --delete
      env:
        LOCAL_DIR: 'wp-content/themes/pp'
        REMOTE_DIR: 'wp-content/themes/pp'
        # --delete arg will delete files on the server if you've deleted them in git
     

  

    
